name: Renovate

on:
  schedule:
    - cron: '5 5,11 * * 1,2,3,4,5'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run Renovate in dry-run mode'
        required: false
        type: choice
        options:
          - 'extract'
          - 'lookup'
          - 'full'
          - 'off'
        default: 'off'

permissions: {}

concurrency:
  group: renovate

env:
  RENOVATE_CONFIGURATION: renovate-runner-config.json
  RENOVATE_IMAGE: ghcr.io/renovatebot/renovate
  RENOVATE_VERSION: 41.115.2 # renovate: datasource=github-releases depName=renovatebot/renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get application token
        id: get_token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run self-hosted Renovate (Dry Run)
        if: ${{ github.event.inputs.dry_run && github.event.inputs.dry_run != 'off' }}
        uses: renovatebot/github-action@5712c6a41dea6cdf32c72d92a763bd417e6606aa # v44.0.5
        with:
          configurationFile: ${{ env.RENOVATE_CONFIGURATION }}
          token: ${{ steps.get_token.outputs.token }}
          renovate-image: ${{ env.RENOVATE_IMAGE }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dry_run }}

      - name: Run self-hosted Renovate
        if: ${{ !github.event.inputs.dry_run || github.event.inputs.dry_run == 'off' }}
        uses: renovatebot/github-action@5712c6a41dea6cdf32c72d92a763bd417e6606aa # v44.0.5
        with:
          configurationFile: ${{ env.RENOVATE_CONFIGURATION }}
          token: ${{ steps.get_token.outputs.token }}
          renovate-image: ${{ env.RENOVATE_IMAGE }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
